# Numpy Tutorial Notes

In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [4]:
a.ndim

1

In [5]:
a.shape

(3,)

In [6]:
a.dtype

dtype('int64')

In [7]:
# specify the type
a = np.array([1, 2, 3], dtype='int8')
a.dtype

dtype('int8')

In [10]:
# size of an item
a.itemsize

1

In [12]:
# size of array
a.size

3

In [13]:
# size of an entire list
a.nbytes

3

## Accessing/Changing specific elements. rows, columns, etc

In [19]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])

In [22]:
# Get a specific row
a[1][:] # or a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [23]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [28]:
# Start startIndex:endIndex:stepSize
a[0, 1:6:2]

array([2, 4, 6])

#### 3D example

In [30]:
b = np.array([[[1, 2, 3], [3, 4, 5], [5, 6, 7], [7, 8, 9]]])
b

array([[[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7],
        [7, 8, 9]]])

In [38]:
b[:, 1, :-1]

array([[3, 4]])

## Initializing different types of arrays

In [40]:
np.zeros((2,3,3,2), dtype='int32') # also np.ones()

array([[[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]]]], dtype=int32)

In [41]:
np.full((2,2), 7)

array([[7, 7],
       [7, 7]])

In [42]:
# RANDOM NUMBER ARRAY
np.random.random_sample(a.shape)

array([[0.46738211, 0.48041949, 0.73898675, 0.51598698, 0.79168221,
        0.03861276, 0.78269496],
       [0.58041102, 0.76751126, 0.72708604, 0.84754593, 0.0135592 ,
        0.58891405, 0.82994817]])

In [44]:
# randon integer numbers
np.random.randint(7, size=(3,3))

array([[1, 2, 2],
       [1, 3, 1],
       [0, 5, 5]])