# Numpy Tutorial Notes

In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [4]:
a.ndim

1

In [5]:
a.shape

(3,)

In [6]:
a.dtype

dtype('int64')

In [7]:
# specify the type
a = np.array([1, 2, 3], dtype='int8')
a.dtype

dtype('int8')

In [10]:
# size of an item
a.itemsize

1

In [12]:
# size of array
a.size

3

In [13]:
# size of an entire list
a.nbytes

3

## Accessing/Changing specific elements. rows, columns, etc

In [19]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])

In [22]:
# Get a specific row
a[1][:] # or a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [23]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [28]:
# Start startIndex:endIndex:stepSize
a[0, 1:6:2]

array([2, 4, 6])

#### 3D example

In [30]:
b = np.array([[[1, 2, 3], [3, 4, 5], [5, 6, 7], [7, 8, 9]]])
b

array([[[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7],
        [7, 8, 9]]])

In [38]:
b[:, 1, :-1]

array([[3, 4]])

## Initializing different types of arrays

In [40]:
np.zeros((2,3,3,2), dtype='int32') # also np.ones()

array([[[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]]]], dtype=int32)

In [41]:
np.full((2,2), 7)

array([[7, 7],
       [7, 7]])

In [42]:
# RANDOM NUMBER ARRAY
np.random.random_sample(a.shape)

array([[0.46738211, 0.48041949, 0.73898675, 0.51598698, 0.79168221,
        0.03861276, 0.78269496],
       [0.58041102, 0.76751126, 0.72708604, 0.84754593, 0.0135592 ,
        0.58891405, 0.82994817]])

In [45]:
# randon integer numbers
np.random.randint(7, size=(3,3))

array([[1, 1, 3],
       [1, 1, 2],
       [1, 1, 3]])

In [50]:
# Repeat an array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

## Copying arrays

In [51]:
a = np.array([1, 2, 3])
b = a
b[0] = 100
b

array([100,   2,   3])

In [52]:
a

array([100,   2,   3])

**b is a pointer to a**

In [54]:
b = a.copy()
b[0] = 13
b

array([13,  2,  3])

In [55]:
a

array([100,   2,   3])

## Statistics

In [70]:
s = np.random.randint(100, size=(3,3, 3))
s

array([[[16, 80, 62],
        [80, 18, 34],
        [57, 10,  6]],

       [[56, 90, 11],
        [97, 21, 61],
        [15, 74, 87]],

       [[13, 66, 19],
        [92, 23, 31],
        [44, 37, 99]]])

In [71]:
np.min(s)

6

In [80]:
np.max(s, axis=2)

array([[80, 80, 57],
       [90, 97, 87],
       [66, 92, 99]])

In [63]:
np.sum(s, axis=0)

array([5, 7, 9])

## Reorganizing arrays

In [93]:
before = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])

after = before.reshape((1,4,2))
after

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

**!!Vertical Stacking!!**

In [124]:
# Vertically staching vactors
v1 = np.random.randint(10, size=(5,10))
v2 = np.ones((1,10), dtype='int64')
v1

array([[8, 7, 7, 2, 3, 2, 9, 9, 5, 1],
       [3, 4, 2, 9, 1, 9, 2, 3, 4, 8],
       [1, 6, 3, 1, 0, 2, 1, 9, 9, 9],
       [7, 4, 4, 1, 9, 7, 8, 8, 8, 6],
       [8, 3, 3, 4, 6, 1, 8, 2, 4, 0]])

In [125]:
v2

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [126]:
np.vstack([v1, v2])

array([[8, 7, 7, 2, 3, 2, 9, 9, 5, 1],
       [3, 4, 2, 9, 1, 9, 2, 3, 4, 8],
       [1, 6, 3, 1, 0, 2, 1, 9, 9, 9],
       [7, 4, 4, 1, 9, 7, 8, 8, 8, 6],
       [8, 3, 3, 4, 6, 1, 8, 2, 4, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

**Horizontal Stacking**

In [131]:
h1 = np.random.randint(10, size=(2,4))
h2 = np.ones((2,2), dtype='int64')
h1

array([[1, 4, 6, 6],
       [8, 3, 2, 7]])

In [132]:
h2

array([[1, 1],
       [1, 1]])

In [133]:
np.hstack((h1,h2))

array([[1, 4, 6, 6, 1, 1],
       [8, 3, 2, 7, 1, 1]])

## Miscellaneous

In [135]:
ar = np.random.randint(100, size=(599, 100))

In [139]:
# Create a boolean mask where in the data the number is more than 50
mask = ar > 50
mask

array([[False,  True, False, ..., False, False,  True],
       [False, False,  True, ..., False, False,  True],
       [ True,  True, False, ..., False, False,  True],
       ...,
       [ True, False, False, ...,  True,  True,  True],
       [ True,  True, False, ..., False, False,  True],
       [False,  True, False, ...,  True, False,  True]])

In [141]:
# Create an array of values that are greater than 50
ar[ar > 50]

array([56, 77, 74, ..., 51, 92, 60])

In [142]:
# Use any mask
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1,2,8]]

array([2, 3, 9])

In [144]:
# Advanced mask
~((ar > 50) & (ar < 60)) # ~ stands for not

array([[ True, False,  True, ...,  True,  True,  True],
       [ True,  True, False, ...,  True,  True,  True],
       [False,  True,  True, ...,  True,  True,  True],
       ...,
       [False,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True, False],
       [ True,  True,  True, ...,  True,  True,  True]])

In [162]:
# Advanced indexing
ar = np.arange(1, 31)
ar = ar.reshape(6, 5)
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [163]:
ar[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [164]:
ar[[0, 1, 2, 3],[1, 2, 3, 4]]

array([ 2,  8, 14, 20])

In [165]:
ar[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

![matrix](matrix.PNG)